[package]
name = "MCS8Sim"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.12.2"
iced = { version = "0.14.0", features = ["advanced", "tokio"] }
rfd = "0.14.1"
serde = { version = "1.0.210", features = ["derive"] }
toml = "0.8.19"
